# Generated by Django 4.0.5 on 2022-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0002_alter_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=True),
        ),
    ]
