# Generated by Django 4.0.5 on 2022-06-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0005_rename_contact_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_Us',
        ),
        migrations.AlterModelTable(
            name='contact_us',
            table='Contact_Us',
        ),
    ]
