# Generated by Django 4.0.5 on 2022-06-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0006_rename_contact_contact_us_alter_contact_us_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='phone',
        ),
    ]
