# Generated by Django 4.0.5 on 2022-06-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0007_remove_contact_us_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Us',
            new_name='Contact',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
