# Generated by Django 4.0.5 on 2022-06-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0009_rename_contact_enquiry_alter_enquiry_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
