# Generated by Django 4.0.5 on 2022-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0012_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('phone', models.IntegerField(default=True)),
            ],
            options={
                'db_table': 'Information',
            },
        ),
    ]
