# Generated by Django 4.0.5 on 2022-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0013_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=None, max_length=200, upload_to='images/post/'),
        ),
    ]
