# Generated by Django 4.0.5 on 2022-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_F', '0014_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(default=None, max_length=200, upload_to='images/post/'),
        ),
    ]
